/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCredentialsRouteImport } from './routes/api/public/credentials'
import { Route as ApiPublicMSplatRouteImport } from './routes/api/public/m/$'
import { Route as ApiPublicCredentialIdRouteImport } from './routes/api/public/credential/$id'
import { Route as ApiPublicCredentialTokenIdRouteImport } from './routes/api/public/credential/token.$id'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCredentialsRoute = ApiPublicCredentialsRouteImport.update({
  id: '/api/public/credentials',
  path: '/api/public/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMSplatRoute = ApiPublicMSplatRouteImport.update({
  id: '/api/public/m/$',
  path: '/api/public/m/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCredentialIdRoute = ApiPublicCredentialIdRouteImport.update({
  id: '/api/public/credential/$id',
  path: '/api/public/credential/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCredentialTokenIdRoute =
  ApiPublicCredentialTokenIdRouteImport.update({
    id: '/api/public/credential/token/$id',
    path: '/api/public/credential/token/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/api/public/credentials': typeof ApiPublicCredentialsRoute
  '/api/public/credential/$id': typeof ApiPublicCredentialIdRoute
  '/api/public/m/$': typeof ApiPublicMSplatRoute
  '/api/public/credential/token/$id': typeof ApiPublicCredentialTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/api/public/credentials': typeof ApiPublicCredentialsRoute
  '/api/public/credential/$id': typeof ApiPublicCredentialIdRoute
  '/api/public/m/$': typeof ApiPublicMSplatRoute
  '/api/public/credential/token/$id': typeof ApiPublicCredentialTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/api/public/credentials': typeof ApiPublicCredentialsRoute
  '/api/public/credential/$id': typeof ApiPublicCredentialIdRoute
  '/api/public/m/$': typeof ApiPublicMSplatRoute
  '/api/public/credential/token/$id': typeof ApiPublicCredentialTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify'
    | '/api/public/credentials'
    | '/api/public/credential/$id'
    | '/api/public/m/$'
    | '/api/public/credential/token/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify'
    | '/api/public/credentials'
    | '/api/public/credential/$id'
    | '/api/public/m/$'
    | '/api/public/credential/token/$id'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verify'
    | '/api/public/credentials'
    | '/api/public/credential/$id'
    | '/api/public/m/$'
    | '/api/public/credential/token/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  ApiPublicCredentialsRoute: typeof ApiPublicCredentialsRoute
  ApiPublicCredentialIdRoute: typeof ApiPublicCredentialIdRoute
  ApiPublicMSplatRoute: typeof ApiPublicMSplatRoute
  ApiPublicCredentialTokenIdRoute: typeof ApiPublicCredentialTokenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/credentials': {
      id: '/api/public/credentials'
      path: '/api/public/credentials'
      fullPath: '/api/public/credentials'
      preLoaderRoute: typeof ApiPublicCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/m/$': {
      id: '/api/public/m/$'
      path: '/api/public/m/$'
      fullPath: '/api/public/m/$'
      preLoaderRoute: typeof ApiPublicMSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/credential/$id': {
      id: '/api/public/credential/$id'
      path: '/api/public/credential/$id'
      fullPath: '/api/public/credential/$id'
      preLoaderRoute: typeof ApiPublicCredentialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/credential/token/$id': {
      id: '/api/public/credential/token/$id'
      path: '/api/public/credential/token/$id'
      fullPath: '/api/public/credential/token/$id'
      preLoaderRoute: typeof ApiPublicCredentialTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  ApiPublicCredentialsRoute: ApiPublicCredentialsRoute,
  ApiPublicCredentialIdRoute: ApiPublicCredentialIdRoute,
  ApiPublicMSplatRoute: ApiPublicMSplatRoute,
  ApiPublicCredentialTokenIdRoute: ApiPublicCredentialTokenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
